config/routes.rb
Rails.application.routes.draw do
resources :zestimates

get 'zestimates/new'

root 'zestimates#new'
mount Split::Dashboard, at: 'split'

end

app/models/zestimate.rb
class Zestimate < ActiveRecord::Base
end

app/controllers/zestimates_controller.rb
class ZestimatesController < ApplicationController
	http_basic_authenticate_with :name => ENV["ADMIN_USERNAME"], :password => ENV["ADMIN_PASSWORD"], only: :index
	skip_before_filter :verify_authenticity_token
	
	require 'open-uri'

	def index
		@zestimates = Zestimate.all.sort_by{ |t| t.created_at }.reverse #sorts leads by date in reverse order
		@title = "Leads"
	end

	def new
		@title = "Get your Free Home Price Estimate Now!"
		@agent? @@agent = @agent: @@agent = 0
		@explanation_text = ab_test('intro text','Knowledge is power. Especially in our fast-paced real estate market. Enter your address above to get an instant home valuation.','')
		#@test_email_label = ab_test('email_title','Email','Email (optional)')
		#@title = ab_test('form_title','Your Home Price Estimator','Get Your Free Home Price Estimate Now!')
	end

	def show
		@title = "Your Home Value Estimate"
		@zestimate = Zestimate.find(params[:id])
		@agent_contact = @zestimate.agent_contact
		@market_report = @zestimate.market_report
		@contact = @zestimate.contact
		@email = @zestimate.email
		@name = @zestimate.name
		@street = @zestimate.street
		@city = @zestimate.city
		@state = @zestimate.state
		@zipcode = @zestimate.zipcode
		@property_type = @zestimate.property_type
		@zestimate_value = @zestimate.zestimate_value
		@zestimate_low = @zestimate.zestimate_low
		@zestimate_high = @zestimate.zestimate_high
		# (@email || @contact) && (@agent_contact || @market_report)
		# AgentMailer.lead_email(name,email,contact,street,city,state,zipcode,property_type,zestimate_value,zestimate_low,zestimate_high,agent_contact,market_report).deliver_now
	end

	def create
	 	#pull data from the form
		street = params[:zestimate][:street]
		city = params[:zestimate][:city]
		state = params[:zestimate][:state]
		zipcode = params[:zestimate][:zipcode]
		name = params[:zestimate][:name]
		email = params[:zestimate][:email]
		
		@title = "Your Home Value Estimate"
		#call the zillow api
		@ID = ENV["zillow_api_id"]
		#@ID = Figaro.env.zillow_api_id
		#url = 'http://www.zillow.com/webservice/GetSearchResults.htm'
		url = 'http://www.zillow.com/webservice/GetDeepSearchResults.htm' #alternate URL with more data to be used later . . . include usecode, number of bedrooms, last sale date, 
		# read more here: http://www.zillow.com/howto/api/GetDeepSearchResults.htm
		if street == ""
			flash[:danger] = "Please enter a valid street address along wtih a city, state and zipcode"
			redirect_to new_zestimate_path
		else
			#flash[:error] = "this is our message"
			@call_url = url + "?zws-id=" + @ID + "&address=" + street + "&citystatezip=" + city + state + zipcode
			@doc = Nokogiri::HTML(open(@call_url))
			@code = @doc.at_xpath("//code").content
			# flash[:error] = @code
			if @code != "0" || @doc.at_xpath("//amount").content == ""
				flash[:danger] = "Please enter a valid street address along wtih a city, state and zipcode"
					#flash[:error] = @call_url
				redirect_to new_zestimate_path
			else
				@street = @doc.at_xpath("//street").content
				@city = @doc.at_xpath("//city").content
				@state = @doc.at_xpath("//state").content
				@zipcode = @doc.at_xpath("//zipcode").content
				@zestimate_value = @doc.at_xpath("//amount").content
				@zestimate_low = @doc.at_xpath("//low").content
				@zestimate_high = @doc.at_xpath("//high").content
				@property_type = @doc.at_xpath("//usecode")
				@property_type = /([A-Z][a-zA-Z\d]+)/.match(@property_type)[0]
				@homedetails = @doc.at_xpath("//homedetails").content
				@zestimate = Zestimate.new(zestimate_params)
				@zestimate.save
				@zestimate.update_attributes(:property_type => @property_type, :zestimate_value => @zestimate_value, :zestimate_low => @zestimate_low, :zestimate_high => @zestimate_high)
				#finished('form_title')
				finished('email_title')
				#@zestimate = Zestimate.new(name: name, email: email, street: @street, city: @city, state: @state, zipcode: @zipcode, property_type: @property_type)
			end	
		end

	end

	def update
		@title = "Thank you!"
		@zestimate = Zestimate.find(params[:id])
		agent_contact = @zestimate.agent_contact
		market_report = @zestimate.market_report
		contact = @zestimate.contact
		email = @zestimate.email
		name = @zestimate.name
		street = @zestimate.street
		city = @zestimate.city
		state = @zestimate.state
		zipcode = @zestimate.zipcode
		property_type = @zestimate.property_type
		zestimate_value = @zestimate.zestimate_value
		zestimate_low = @zestimate.zestimate_low
		zestimate_high = @zestimate.zestimate_high
		

		if @zestimate.update_attributes(zestimate_params)
			@zestimate = Zestimate.find(params[:id])
			market_report = @zestimate.market_report
			agent_contact = @zestimate.agent_contact
			id = @zestimate.id
			email = @zestimate.email
			contact = @zestimate.contact

			#if (email == "" || !!email.match(/\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/)) && contact == ""
			#if !!email.match(/\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/)
			if (!email.match(/\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/) || email == "") && contact == "" && (agent_contact == 1 || market_report == 1)
				flash[:danger] = "Please enter a valid email or contact info if you would like to receive market reports or be contacted by an agent"
				redirect_to zestimate_path, action: "edit", id: id
			#rewrite this to send an email only if the address has not been 
			# previously assigned AND to send out a lead even if the person hasn't requested info -- rather than scheduling an overnight job -- just handle everything right away. 
			
			elsif market_report == 1 && agent_contact == 1
				flash.now[:success] = "Thanks! An agent will be in touch shortly and you'll receive your first market report soon" 
				AgentMailer.lead_email(id,name,email,contact,street,city,state,zipcode,property_type,zestimate_value,zestimate_low,zestimate_high,agent_contact,market_report).deliver_now
			elsif market_report == 1 && agent_contact == 0
				flash.now[:success] = "Thanks! You'll receive your first market report shortly."
				AgentMailer.lead_email(id,name,email,contact,street,city,state,zipcode,property_type,zestimate_value,zestimate_low,zestimate_high,agent_contact,market_report).deliver_now
			elsif market_report == 0 && agent_contact == 1
				flash.now[:success] = "Thanks! An agent will be touch shortly"
				AgentMailer.lead_email(id,name,email,contact,street,city,state,zipcode,property_type,zestimate_value,zestimate_low,zestimate_high,agent_contact,market_report).deliver_now
			else #submits without requesting any info
				flash.now[:success] = "Thanks for using the ePlace Home Value Estimator!"
				AgentMailer.lead_email(id,name,email,contact,street,city,state,zipcode,property_type,zestimate_value,zestimate_low,zestimate_high,agent_contact,market_report).deliver_now
			end
		else
			render 'edit'
		end 

		

	end


private	
	
	def zestimate_params
		params.require(:zestimate).permit(:id, :name, :email, :street, :city, :state, :zipcode, :property_type, :agent_contact, :market_report, :contact, :comments)
	end	

end

app/helpers/zestimates_helper.rb
module ZestimatesHelper

	def currency(string)
		"$#{string.to_s.gsub(/\d(?=(...)+$)/, '\0,')}"
	end

	def codestring(string)
		string = /([A-Z][a-zA-Z\d]+)/.match(string)[0]
		@output = string
		use_hash = { '' => 'homes', 'SingleFamily' => 'Single Family Homes', 'Duplex' => 'Two-Family Homes', 'Triplex': 'Three-Family Homes', 'Quadruplex' => 'Multi-Family Homes', 'Condominium' => 'Condominium Homes', 'Cooperative' => 'Condominium Homes', 'Mobile' => 'Mobile Homes', 'MultiFamily2To4' => 'Multi-Family Homes', 'MultiFamily5Plus' => 'Multi-Family Homes', 'Timeshare' => 'Timeshares', 'Miscellaneous' => 'Miscellaneous Homes', 'VacantResidentialLand' => 'Land' }
		@output = use_hash[string]	
	end	

	def cleantime(string)
		string = string.to_s.gsub(/ -0\d00/,'')
	end

	def answer(int)
		int == 1? "Yes": "No"
	end	

	def select_agent
		agent_id ||= 1 #set initial agent id
		agent_hash = { 1 => 'rachael@wordaroundtown.com', 2 => 'rachael@eplacehomes.com'}
		@assigned_agent = agent_hash[agent_id]
		agent_id < 2? agent_id += 1: agent_id = 1
	end
end

	# def currency(string)
	# 	newstring = string.split('')
	# 	if newstring.length < 4
	# 		newstring.join.insert(0,'$')
	# 	elsif newstring.length < 7
	# 		newstring.insert(-4,',').insert(0,'$').join
	# 	elsif newstring.length < 10
	# 		newstring.insert(-4,',').insert(-8,',').insert(0,'$').join
	# 	end
	# end

	# def currency(string)
	# 	string.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse.split('').insert(0,'$').join
	# end

app/views/zestimates/_page2.html.erb
<div class="row">
  <div class="col-md-12">
  <h2 style="margin-top:-10px;">for <%= @street %> <%= @city %>, <%= @state %>  <%= @zipcode %></h2>
  </div>
</div> 

<div class="well">
	<div class="row">

		<div class="col-md-4">
			<h3>Low Zestimate<br>
			<%= currency(@zestimate_low) %></h3>
		</div>

		<div class="col-md-4">
			<h2>Your Zestimate<br>
			<%= currency(@zestimate_value) %></h2>
		</div>

		<div class="col-md-4">
			<h3>High Zestimate<br>
			<%= currency(@zestimate_high) %></h3>
		</div>

    <div class="row">
      <div class="col-md-12" style="font-size:85%;">
        <a href="http://www.zillow.com"><img src="http://www.zillow.com/widgets/GetVersionedResource.htm?path=/static/logos/Zillowlogo_150x40_rounded.gif" width="150" height="40" alt="Zillow Real Estate Search" /></a><br>See more information for <a href="<%= @homedetails %>"><%= @street %></a> on Zillow.
      </div>
    </div>

	</div>	

	<%= form_for :zestimate, url: zestimate_path(@zestimate), method: :patch do |f| %>	
 

 <div class="row" style="margin-top: 30px">   	
    <div class="col-md-3">
    </div>

   	<div class="col-md-6">

    	<div class="form-horizontal actioncall">
            <%= f.check_box :market_report, class: 'check-box' %> Send me a monthly market report for <b><%= codestring(@property_type) %></b> in <b><%= @city %></b>
      </div>

      <div class="form-horizontal actioncall">
            <%= f.check_box :agent_contact, class: 'check-box' %>
          	Please have an agent contact me to prepare an opinion of value and marketing plan
      </div>
		    
    	<div class="form-group">
  			<%= f.label :email %>  
  			<%= f.text_field :email, class: "form-control" %>
		</div> 

        <div class="form-group">
        	<%= f.label "Name and Phone Number" %>
        	<%= f.text_field :contact, class: "form-control" %>
        </div>

        <div class="form-group">
        	<%= f.submit "Submit", class: "btn btn-success" %>
        </div>

    <div class="col-md-3">
    </div>

	<% end %>
  </div>

<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '1552984285001398');
fbq('track', "PageView");</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1552984285001398&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->

</div>

app/views/zestimates/create.html.erb
<%= render "zestimates/page2" %>

app/views/zestimates/edit.html.erb
<%= form_for :zestimate, url: zestimate_path(@zestimate), method: :patch do |f| %>	
 

 <div class="row" style="margin-top: 30px">   	
    <div class="col-md-3">
    </div>

    <div class="col-md-6">	
    	<div class="form-horizontal">
          <div class="message">
            <%= f.check_box :market_report, class: 'check-box' %> Send me a monthly market report for <b><%= @property_type %></b> in <b><%= @city %></b>
          </div>
        </div>

        <div class="form-horizontal">  
          <div class="message">
          	<%= f.check_box :agent_contact, class: 'check-box' %>
          	Please have an agent contact me to prepare an opinion of value and marketing plan
          </div>
        </div>
		    
    	<div class="form-group">
  			<%= f.label :email %>  
  			<%= f.text_field :email, class: "form-control" %>
		</div> 

        <div class="form-group">
        	<%= f.label "Name and Phone Number" %>
        	<%= f.text_field :contact, class: "form-control" %>
        </div>

        <div class="form-group">
        	<%= f.submit "Submit" %>
        </div>

    <div class="col-md-3">
    </div>

	<% end %>
</div>
</div>

app/views/zestimates/index.html.erb
<div class="well">
  <table class="table">
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>Zestimate</th>
      <th>Name</th>
      <th>Email</th>
      <th>Contact</th>
      <th>Market Report</th>
      <th>Agent Contact</th>
      <th>Assigned Agent</th>
      <th>Date</th>

    </tr>
   
    <% @zestimates.each do |zestimate| %>
      <tr>
        <td><%= zestimate.street %></td>
        <td><%= zestimate.city %></td>
        <td><%= zestimate.state %></td>
        <td><%= zestimate.zipcode %></td>
        <td><%= currency(zestimate.zestimate_value) %></td>
        <td><%= zestimate.name %></td>
        <td><%= zestimate.email %></td>
        <td><%= zestimate.contact %></td>
        <td><%= answer(zestimate.market_report) %></td>
        <td><%= answer(zestimate.agent_contact) %></td>
        <td><%= zestimate.assigned_agent %></td>
        <td><%= cleantime(zestimate.created_at) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/zestimates/new.html.erb
<div class="row">
  <div class="col-md-3">
  </div>

  <div class="col-md-6">
    <div class="well">


      <%= form_for :zestimate, url: zestimates_path do |f| %>
        
        <!--<div class="from-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label(:email, @test_email_label) %>  
          <%= f.text_field :email, class: "form-control" %>
        </div>-->

        <div class="form-group">
          <%= f.label :street, "Street Address" %>  
          <%= f.text_field :street, class: "form-control" %>
        </div>

        <div class="form-group row">
          <div class="col-md-5">  
            <%= f.label :city %>
            <%= f.text_field :city, class: "form-control" %>
          </div>

          <div class="col-md-2">
            <%= f.label :state %>
            <div class="dropdown">
              <%= f.select :state, options_for_select(["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],"MA"), class: "dropdown-menu" %>
            </div>
          </div>
     
          <div class="col-md-5"> 
            <%= f.label :zipcode, "ZIP" %>
            <%= f.text_field :zipcode, class: "form-control" %>
          </div>

        </div> 
  
      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-success" %>
      </div>  

      <div class="form-group">
          <%= @explanation_text %>
      </div>

    <% end %>

    </div>
  </div>
  
  <div class="col-md-3">
  </div>

</div>  


  <div class="container">
  </div>

app/views/zestimates/show.html.erb
<%= render "zestimates/page2" %>

app/views/zestimates/update.html.erb
<div class="well">
	Any questions? Ring us at 617.864.4600 or <a href="mailto: info@eplacehomes.com">email us</a>. 
</div>	